name: Deploy My Server

on:
  push:
    branches:
      - main # 只在master上push触发部署
      
jobs:
  deploy:
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本
    steps:
      - uses: actions/checkout@v1 
      - name: Deploy to Staging My server
        uses: easingthemes/ssh-deploy@v2.1.6
        env:
          #私钥
          SSH_PRIVATE_KEY: ${{ secrets.MY_TENCENT_SERVER_PRIVATE_SECRET_KEY }} #后面指定为该仓库配置的私钥
          ARGS: "-rltgoDzvO"
          SOURCE: '/'
          REMOTE_HOST: '124.221.154.95'
          REMOTE_USER: 'root'
          TARGET: '/home/blog/'
