name: docs

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # 选择要使用的 node 版本
          node-version: 18
          # 缓存 pnpm 依赖
          cache: npm

      # 运行构建脚本
      - name: Build VuePress site
        run: npm docs:build

      # 部署到腾讯云服务器
      - name: Deploy to Staging My server
        uses: easingthemes/ssh-deploy@v2.1.6
        env:
          #私钥
          SSH_PRIVATE_KEY: ${{ secrets.MY_TENCENT_SERVER_PRIVATE_SECRET_KEY }} #后面指定为该仓库配置的私钥
          ARGS: "-rltgoDzvO"
          SOURCE: 'docs/.vuepress/dist'
          REMOTE_HOST: '124.221.154.95'
          REMOTE_USER: 'root'
          TARGET: '/home/blog/'
